# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- dev


pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Job1
  steps:
  - script: echo Job1 - Hello, world, changed!
    displayName: 'Run a one-line script'
  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo more information
    displayName: 'Run a multi-line script'